"""Watson mass-dependent (r_m) structure fitting.

The physical claim -- that I_obs = I_m + c sqrt(I_m) describes real
rovibrational offsets -- is Watson's, and these tests do not try to relitigate
it. What they check is that the fitting machinery is correct *as a fitting
machine*: given data generated from a model with known parameters, it must
recover those parameters and that structure. That is the part this repository
is responsible for, and the part a regression would break silently.
"""

import sys
from pathlib import Path

import numpy as np
import pytest

_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(_ROOT / ".github"))
sys.path.insert(0, str(_ROOT))

from backend.spectral.centrifugal_distortion import (  # noqa: E402
    _INERTIA_TO_MHZ,
    rotational_constants_mhz,
)
from backend.spectral.mass_dependent import (  # noqa: E402
    fit_mass_dependent_structure,
    moments_amu_ang2,
    moments_from_constants_mhz,
    predicted_moments,
    watson_rho,
)

M_H, M_D, M_C12, M_C13, M_O16, M_O18 = (
    1.00782503207, 2.0141017778, 12.0, 13.0033548378, 15.9949146196, 17.9991610)


def _water(r=0.9578, deg=104.48):
    th = np.radians(deg)
    return np.array([
        [0.0, 0.0, 0.0],
        [r * np.sin(th / 2), r * np.cos(th / 2), 0.0],
        [-r * np.sin(th / 2), r * np.cos(th / 2), 0.0],
    ])


def _h2co(rco=1.205, rch=1.111, deg=121.9):
    """Formaldehyde: four atoms, three isotopic handles, genuinely planar."""
    th = np.radians(deg)
    return np.array([
        [0.0, 0.0, 0.0],
        [0.0, 0.0, rco],
        [rch * np.sin(th), 0.0, -rch * np.cos(th)],
        [-rch * np.sin(th), 0.0, -rch * np.cos(th)],
    ])


def _species(coords, mass_sets, c=None, d=None, sigma_rel=0.0, seed=0):
    """Synthetic isotopologues generated from a known structure and model."""
    rng = np.random.default_rng(seed)
    out = []
    for name, masses in mass_sets:
        i_pred = predicted_moments(coords, masses, c, d)
        const = _INERTIA_TO_MHZ / i_pred          # B = k / I
        if sigma_rel:
            const = const * (1.0 + sigma_rel * rng.standard_normal(const.size))
        out.append({
            "name": name,
            "masses": np.asarray(masses, dtype=float),
            "obs_constants": const,
            "sigma_constants": np.abs(const) * max(sigma_rel, 1e-6),
        })
    return out


WATER_SETS = [
    ("H2-16O", [M_O16, M_H, M_H]),
    ("H2-18O", [M_O18, M_H, M_H]),
    ("D2-16O", [M_O16, M_D, M_D]),
    ("HD-16O", [M_O16, M_H, M_D]),
]

H2CO_SETS = [
    ("H2-12C-16O", [M_C12, M_O16, M_H, M_H]),
    ("H2-13C-16O", [M_C13, M_O16, M_H, M_H]),
    ("H2-12C-18O", [M_C12, M_O18, M_H, M_H]),
    ("D2-12C-16O", [M_C12, M_O16, M_D, M_D]),
    ("HD-12C-16O", [M_C12, M_O16, M_H, M_D]),
    ("D2-13C-18O", [M_C13, M_O18, M_D, M_D]),
]


def _bond_rms(a, b, pairs):
    """RMS difference in bond lengths, which is rotation/translation invariant."""
    da = [np.linalg.norm(a[i] - a[j]) for i, j in pairs]
    db = [np.linalg.norm(b[i] - b[j]) for i, j in pairs]
    return float(np.sqrt(np.mean((np.array(da) - np.array(db)) ** 2)))


def test_moments_round_trip_through_constants():
    """Moments -> constants -> moments must be the identity."""
    coords = _water()
    masses = np.array([M_O16, M_H, M_H])
    i_direct = moments_amu_ang2(coords, masses)
    i_round = moments_from_constants_mhz(rotational_constants_mhz(coords, masses))
    assert np.allclose(i_direct, np.sort(i_round), rtol=1e-10)


def test_r0_recovers_the_structure_it_was_generated_from():
    """With no mass dependence, the rigid fit must return the exact structure."""
    truth = _h2co()
    isos = _species(truth, H2CO_SETS)
    fit = fit_mass_dependent_structure(isos, truth + 0.02, model="r0")
    assert fit.converged
    assert _bond_rms(fit.coords, truth, [(0, 1), (0, 2), (0, 3)]) < 1e-4


def test_rm1_recovers_both_structure_and_coefficients():
    """The point of the method: separate the structure from the offset."""
    truth = _h2co()
    c_true = np.array([0.012, 0.030, 0.045])
    isos = _species(truth, H2CO_SETS, c=c_true)
    fit = fit_mass_dependent_structure(isos, truth + 0.02, model="rm1")
    assert fit.converged
    assert _bond_rms(fit.coords, truth, [(0, 1), (0, 2), (0, 3)]) < 1e-3, (
        "structure not recovered from data generated by the same model"
    )
    assert np.allclose(fit.c, c_true, atol=2e-3), f"c not recovered: {fit.c}"


def test_rm1_beats_r0_when_the_data_has_a_mass_dependent_offset():
    """This is the whole reason the model exists.

    Data carrying a rovibrational-style offset is fitted by both models. The
    rigid fit has to absorb the offset into the geometry -- that is exactly what
    makes an r_0 structure differ from r_e -- while r_m1 can put it where it
    belongs.
    """
    truth = _h2co()
    c_true = np.array([0.02, 0.05, 0.07])
    isos = _species(truth, H2CO_SETS, c=c_true)
    pairs = [(0, 1), (0, 2), (0, 3)]
    err_r0 = _bond_rms(
        fit_mass_dependent_structure(isos, truth + 0.02, model="r0").coords, truth, pairs)
    err_rm1 = _bond_rms(
        fit_mass_dependent_structure(isos, truth + 0.02, model="rm1").coords, truth, pairs)
    assert err_rm1 < 0.1 * err_r0, (
        f"r_m1 {err_rm1 * 1000:.2f} mA did not clearly beat r_0 {err_r0 * 1000:.2f} mA"
    )


def test_rm2_recovers_its_own_extra_term():
    truth = _h2co()
    c_true = np.array([0.010, 0.020, 0.030])
    d_true = np.array([0.05, -0.04, 0.06])
    isos = _species(truth, H2CO_SETS, c=c_true, d=d_true)
    fit = fit_mass_dependent_structure(isos, truth + 0.01, model="rm2")
    assert fit.converged
    assert _bond_rms(fit.coords, truth, [(0, 1), (0, 2), (0, 3)]) < 2e-3
    assert np.allclose(fit.d, d_true, atol=1e-2), f"d not recovered: {fit.d}"


def test_watson_rho_does_not_overflow_on_a_large_molecule():
    """The mass product overflows long before the molecule gets interesting."""
    rho = watson_rho([12.0] * 60 + [1.0] * 60)
    assert np.isfinite(rho) and rho > 0


def test_symmetry_constraint_is_honoured():
    """A C2v fit must not return water with two different O-H bonds."""
    from backend.symmetry import create_symmetry
    truth = _water()
    isos = _species(truth, WATER_SETS, c=np.array([0.01, 0.02, 0.03]))
    sym = create_symmetry("auto", ["O", "H", "H"], truth)
    assert sym.point_group == "C2v"
    fit = fit_mass_dependent_structure(isos, truth + 0.01, model="rm1", symmetry=sym)
    oh1 = np.linalg.norm(fit.coords[1] - fit.coords[0])
    oh2 = np.linalg.norm(fit.coords[2] - fit.coords[0])
    assert abs(oh1 - oh2) < 1e-9, f"symmetry broken: {oh1:.6f} vs {oh2:.6f}"


def test_underdetermined_fit_says_so_rather_than_reporting_a_chi_square():
    """One species cannot separate structure from mass dependence.

    Rank alone cannot detect this -- it is bounded by the number of
    observations, so a starved fit still reports dof >= 0. The flag has to come
    from comparing what the data fix against what the model could fix if every
    constant of every species were measured.
    """
    truth = _water()
    isos = _species(truth, WATER_SETS[:1])
    fit = fit_mass_dependent_structure(isos, truth, model="rm1")
    assert fit.underdetermined, (
        f"{fit.n_params} of {fit.n_determinable} determined but not flagged"
    )
    assert fit.n_params < fit.n_determinable
    assert any("under-determined" in w for w in fit.warnings)
    assert any("isotopologue" in w for w in fit.warnings)


def test_a_well_fed_fit_is_not_flagged_as_underdetermined():
    """The counterpart: four species of water do determine the model.

    Water rather than formaldehyde, because a three-atom molecule has no
    out-of-plane internal coordinate -- see the next test.
    """
    truth = _water()
    isos = _species(truth, WATER_SETS, c=np.array([0.01, 0.02, 0.03]))
    fit = fit_mass_dependent_structure(isos, truth + 0.01, model="rm1")
    assert not fit.underdetermined, (
        f"{fit.n_params} of {fit.n_determinable} determined"
    )
    assert fit.dof > 0
    assert fit.reduced_chi2 is not None


@pytest.mark.parametrize("model", ["r0", "rm1", "rm2"])
def test_planar_molecules_lose_exactly_the_out_of_plane_coordinate(model):
    """A planar geometry cannot pin its own out-of-plane bend, at any order.

    Displacing an atom perpendicular to the molecular plane changes the moments
    only at second order -- the first derivative vanishes by symmetry -- so a
    linear fit sees nothing along that direction no matter how many species are
    supplied. Formaldehyde has one such coordinate and the fit is short by
    exactly one, in every model. This is a property of the geometry, not of the
    data, which is why adding the c and d terms does not change the shortfall.
    """
    truth = _h2co()
    c = np.array([0.01, 0.02, 0.03]) if model != "r0" else None
    isos = _species(truth, H2CO_SETS, c=c)
    fit = fit_mass_dependent_structure(isos, truth + 0.01, model=model)
    assert fit.n_determinable - fit.n_params == 1, (
        f"expected exactly the out-of-plane coordinate to be lost, got "
        f"{fit.n_determinable - fit.n_params} undetermined directions"
    )
    assert fit.underdetermined
    # Water, with three atoms, has no out-of-plane coordinate to lose.
    water = _water()
    w_isos = _species(water, WATER_SETS,
                      c=(None if model == "r0" else np.array([0.01, 0.02, 0.03])))
    w_fit = fit_mass_dependent_structure(w_isos, water + 0.01, model=model)
    assert w_fit.n_determinable == w_fit.n_params


def test_partial_constants_are_used_not_dropped():
    """A species with only B measured still constrains the fit."""
    truth = _h2co()
    isos = _species(truth, H2CO_SETS, c=np.array([0.01, 0.02, 0.03]))
    full = fit_mass_dependent_structure(isos, truth + 0.01, model="rm1")
    isos[-1]["component_indices"] = np.array([1])
    isos[-1]["obs_constants"] = isos[-1]["obs_constants"][[1]]
    isos[-1]["sigma_constants"] = isos[-1]["sigma_constants"][[1]]
    partial = fit_mass_dependent_structure(isos, truth + 0.01, model="rm1")
    assert partial.n_obs == full.n_obs - 2
    assert partial.converged


@pytest.mark.parametrize("model", ["r0", "rm1", "rm2"])
def test_every_model_runs_and_reports_consistent_bookkeeping(model):
    truth = _h2co()
    isos = _species(truth, H2CO_SETS)
    fit = fit_mass_dependent_structure(isos, truth + 0.01, model=model)
    n_coeff = {"r0": 0, "rm1": 3, "rm2": 6}[model]
    assert fit.model == model
    assert fit.n_obs == sum(len(i["obs_constants"]) for i in isos)
    assert fit.n_params_raw == 3 * truth.shape[0] + n_coeff
    # n_params is the rank, so it can never exceed either the raw count or the
    # number of observations, and it must leave room for the rigid-body
    # directions that no moment can see.
    assert fit.n_params <= min(fit.n_params_raw, fit.n_obs)
    # Six rigid-body directions are invisible to any moment, so they can never
    # be among the determinable ones.
    assert fit.n_determinable == fit.n_params_raw - 6
    assert fit.dof == fit.n_obs - fit.n_params
    assert np.isfinite(fit.rms_moment)
